orbs:
  python: circleci/python@1.1.0
version: 2.1

jobs:
  lint-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: dev-requirements.txt
      - run:
          name: Flake8
          command: flake8 .
      - run:
          name: Black Format check
          command: black --check .
      - run:
          name: Test
          command: pytest tests
  build-and-deploy:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: dev-requirements.txt
      - run:
          name: Verify Git tag and version
          command: python setup.py verify
      - python/dist
      - run:
          name: Publish to Pypi
          command: twine upload dist/*

        
workflows:
  main:
    jobs:
      - lint-and-test:
          filters: 
            tags:
              only: /.*/
      - build-and-deploy:
          requires:
            - lint-and-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
